### PR TITLE
Added missing dependencies

### PR DESCRIPTION
**Pull request by tcrous**
Added missing
("content", "0001_initial"),
("communication", "0009_initial"),
to core migration.

### CODE REVIEW

**Comment by tcrous** [comment]
Fixed error in migrate

**Comment by smn** [comment]
New error :) 

```
DETAIL:  Key (course_id)=(1) is not present in table "organisation_course".
```

While it may seem a pain now, over time Travis & tests save a _ton_ of time.

**Comment by smn** [comment]
From IRC:

```
11:54 <sdehaan> theocrous: check https://gist.github.com/c6da47bc25cec35f432e
11:54 <sdehaan> theocrous: since your fixtures are only installed after migration you can ensure their order by making sure the migrations are ordered properly
```

**Comment by smn** [comment]
Clicky: https://gist.github.com/c6da47bc25cec35f432e

**Comment by smn** [comment]
Fixed fixtures by loading them manually with data migrations instead of relying on when Django or South thinks it should do them.

**Pull request merged**
