### PR TITLE
DIG-32 Migrate questions to close gaps in question order.

### PR DESCRIPTION
**Pull request by rjacobs31**
Hi, @msinovcic. Could you please look over this for me? It should be updating question order from a point of overlap until there is no more overlap.

### CODE REVIEW

**Comment by msinovcic** [comment]
👍

**Comment by rjacobs31** [comment]
Hi, @bruskiza. Just want to make doubly sure before merging this and migrating the files.
This should:
a) get the highest order when creating new questions, not the question count;
b) sort existing questions by order (grouped by module) and bump the order number of duplicates until there are no duplicates (via migration).

**Comment by rjacobs31** [comment]
On second thought, perhaps doing it globally isn't the best idea. I think it should only adjust the questions mentioned on the support ticket.

**Comment by dbreedt** [comment]
@rjacobs31 As discussed this morning, please add tests that validate your updated order calculations.

**Comment by dbreedt** [comment]
:+1:

**Pull request merged**
